version: '3'
services:
    pwn:
        security_opt:
          - seccomp:unconfined
        cap_add:
          - SYS_PTRACE
        container_name: pwn
        build: ./pwn
        ports:
            - "31338:31338"
